#!/bin/sh

FEDORA_MIRROR=https://dl.fedoraproject.org
DEBIAN_MIRROR=https://mirrors.kernel.org


s='[[:space:]]'
eq="$s*=$s*"

# switch from metalink/mirrorlist to baseurl because stable URLs are needed
exp1="s/^\($s*\(metalink\|mirrorlist\)$eq\)/#\1/"
exp2="s/^$s*#$s*\(baseurl$eq\)/\1/"

# switch from mirror rotations to specific HTTPS mirrors
exp3="s@http://download\.fedoraproject\.org/@$FEDORA_MIRROR/@"
exp4="s@http://\(http\.debian\.net\|ftp\.us\.debian\.org\)/@$DEBIAN_MIRROR/@"

# switch some more hosts from HTTP to HTTPS
exp5="s@http://\(www\.whonix\.org\|deb\.torproject\.org\|dl\.google\.com\)/@https://\1/@"

# ensure that the updates cache address is prepended to URLs
exp6="/baseurl$eq\|deb$s\|deb-src$s/s@\([^/]\)\(\(http\|https\|ftp\)://[^1]\)@\1http://10.137.255.254:8083/\2@"

find /etc/yum.repos.d/*.repo \
     /etc/apt/sources.list.d/*.list \
     /etc/apt/sources.list \
     -print0 2>/dev/null |  # to ignore error messages from missing files
xargs -0 sed -i.bak \
             -e "$exp1" \
             -e "$exp2" \
             -e "$exp3" \
             -e "$exp4" \
             -e "$exp5" \
             -e "$exp6"
