#!/bin/sh
set -ex

id=vm-updates

getent passwd $id >/dev/null ||
useradd --shell /bin/false --home / --system --user-group $id

install -d -m 750 -o $id -g $id "$DESTDIR"/var/lib/qubes/$id
umask 022
cp -R etc usr "$DESTDIR"/
