#!/bin/sh

RULE_FILTER="INPUT -i vif+ -p tcp --dport 8083 -j ACCEPT"
RULE_NAT="PR-QBS-SERVICES -i vif+ -d 10.137.255.254 -p tcp --dport 8083 -j REDIRECT"

STATUS=0

if [ "$1" = "stop" ]; then
    iptables -w -t filter -D $RULE_FILTER
    iptables -w -t nat    -D $RULE_NAT
elif [ -e /var/run/qubes-service/qubes-updates-cache ]; then  # start
    iptables -w -t filter -C $RULE_FILTER ||
    iptables -w -t filter -I $RULE_FILTER ||
    STATUS=1
    iptables -w -t nat    -C $RULE_NAT ||
    iptables -w -t nat    -I $RULE_NAT ||
    STATUS=1

    # Work around https://github.com/QubesOS/qubes-issues/issues/1555
    # ("Updates proxy fails to set iptables rules in ProxyVM")  XXX
    symlink=/rw/config/qubes_firewall_user_script  # yes, the legacy path
    target=/usr/lib/qubes/updates-cache-iptables
    [ "$(readlink $symlink)" = $target ] ||
    ln -s $target $symlink               ||
    STATUS=1
fi

exit $STATUS
